// Code generated by protoc-gen-go. DO NOT EDIT.
// source: replication/pdu/pdu.proto

package pdu

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FilesystemVersion_VersionType int32

const (
	FilesystemVersion_Snapshot FilesystemVersion_VersionType = 0
	FilesystemVersion_Bookmark FilesystemVersion_VersionType = 1
)

var FilesystemVersion_VersionType_name = map[int32]string{
	0: "Snapshot",
	1: "Bookmark",
}

var FilesystemVersion_VersionType_value = map[string]int32{
	"Snapshot": 0,
	"Bookmark": 1,
}

func (x FilesystemVersion_VersionType) String() string {
	return proto.EnumName(FilesystemVersion_VersionType_name, int32(x))
}

func (FilesystemVersion_VersionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_368839fb4f2ad628, []int{5, 0}
}

type ListFilesystemReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListFilesystemReq) Reset()         { *m = ListFilesystemReq{} }
func (m *ListFilesystemReq) String() string { return proto.CompactTextString(m) }
func (*ListFilesystemReq) ProtoMessage()    {}
func (*ListFilesystemReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_368839fb4f2ad628, []int{0}
}

func (m *ListFilesystemReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListFilesystemReq.Unmarshal(m, b)
}
func (m *ListFilesystemReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListFilesystemReq.Marshal(b, m, deterministic)
}
func (m *ListFilesystemReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListFilesystemReq.Merge(m, src)
}
func (m *ListFilesystemReq) XXX_Size() int {
	return xxx_messageInfo_ListFilesystemReq.Size(m)
}
func (m *ListFilesystemReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListFilesystemReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListFilesystemReq proto.InternalMessageInfo

type ListFilesystemRes struct {
	Filesystems          []*Filesystem `protobuf:"bytes,1,rep,name=Filesystems,proto3" json:"Filesystems,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ListFilesystemRes) Reset()         { *m = ListFilesystemRes{} }
func (m *ListFilesystemRes) String() string { return proto.CompactTextString(m) }
func (*ListFilesystemRes) ProtoMessage()    {}
func (*ListFilesystemRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_368839fb4f2ad628, []int{1}
}

func (m *ListFilesystemRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListFilesystemRes.Unmarshal(m, b)
}
func (m *ListFilesystemRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListFilesystemRes.Marshal(b, m, deterministic)
}
func (m *ListFilesystemRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListFilesystemRes.Merge(m, src)
}
func (m *ListFilesystemRes) XXX_Size() int {
	return xxx_messageInfo_ListFilesystemRes.Size(m)
}
func (m *ListFilesystemRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ListFilesystemRes.DiscardUnknown(m)
}

var xxx_messageInfo_ListFilesystemRes proto.InternalMessageInfo

func (m *ListFilesystemRes) GetFilesystems() []*Filesystem {
	if m != nil {
		return m.Filesystems
	}
	return nil
}

type Filesystem struct {
	Path                 string   `protobuf:"bytes,1,opt,name=Path,proto3" json:"Path,omitempty"`
	ResumeToken          string   `protobuf:"bytes,2,opt,name=ResumeToken,proto3" json:"ResumeToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Filesystem) Reset()         { *m = Filesystem{} }
func (m *Filesystem) String() string { return proto.CompactTextString(m) }
func (*Filesystem) ProtoMessage()    {}
func (*Filesystem) Descriptor() ([]byte, []int) {
	return fileDescriptor_368839fb4f2ad628, []int{2}
}

func (m *Filesystem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Filesystem.Unmarshal(m, b)
}
func (m *Filesystem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Filesystem.Marshal(b, m, deterministic)
}
func (m *Filesystem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Filesystem.Merge(m, src)
}
func (m *Filesystem) XXX_Size() int {
	return xxx_messageInfo_Filesystem.Size(m)
}
func (m *Filesystem) XXX_DiscardUnknown() {
	xxx_messageInfo_Filesystem.DiscardUnknown(m)
}

var xxx_messageInfo_Filesystem proto.InternalMessageInfo

func (m *Filesystem) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Filesystem) GetResumeToken() string {
	if m != nil {
		return m.ResumeToken
	}
	return ""
}

type ListFilesystemVersionsReq struct {
	Filesystem           string   `protobuf:"bytes,1,opt,name=Filesystem,proto3" json:"Filesystem,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListFilesystemVersionsReq) Reset()         { *m = ListFilesystemVersionsReq{} }
func (m *ListFilesystemVersionsReq) String() string { return proto.CompactTextString(m) }
func (*ListFilesystemVersionsReq) ProtoMessage()    {}
func (*ListFilesystemVersionsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_368839fb4f2ad628, []int{3}
}

func (m *ListFilesystemVersionsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListFilesystemVersionsReq.Unmarshal(m, b)
}
func (m *ListFilesystemVersionsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListFilesystemVersionsReq.Marshal(b, m, deterministic)
}
func (m *ListFilesystemVersionsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListFilesystemVersionsReq.Merge(m, src)
}
func (m *ListFilesystemVersionsReq) XXX_Size() int {
	return xxx_messageInfo_ListFilesystemVersionsReq.Size(m)
}
func (m *ListFilesystemVersionsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListFilesystemVersionsReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListFilesystemVersionsReq proto.InternalMessageInfo

func (m *ListFilesystemVersionsReq) GetFilesystem() string {
	if m != nil {
		return m.Filesystem
	}
	return ""
}

type ListFilesystemVersionsRes struct {
	Versions             []*FilesystemVersion `protobuf:"bytes,1,rep,name=Versions,proto3" json:"Versions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ListFilesystemVersionsRes) Reset()         { *m = ListFilesystemVersionsRes{} }
func (m *ListFilesystemVersionsRes) String() string { return proto.CompactTextString(m) }
func (*ListFilesystemVersionsRes) ProtoMessage()    {}
func (*ListFilesystemVersionsRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_368839fb4f2ad628, []int{4}
}

func (m *ListFilesystemVersionsRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListFilesystemVersionsRes.Unmarshal(m, b)
}
func (m *ListFilesystemVersionsRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListFilesystemVersionsRes.Marshal(b, m, deterministic)
}
func (m *ListFilesystemVersionsRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListFilesystemVersionsRes.Merge(m, src)
}
func (m *ListFilesystemVersionsRes) XXX_Size() int {
	return xxx_messageInfo_ListFilesystemVersionsRes.Size(m)
}
func (m *ListFilesystemVersionsRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ListFilesystemVersionsRes.DiscardUnknown(m)
}

var xxx_messageInfo_ListFilesystemVersionsRes proto.InternalMessageInfo

func (m *ListFilesystemVersionsRes) GetVersions() []*FilesystemVersion {
	if m != nil {
		return m.Versions
	}
	return nil
}

type FilesystemVersion struct {
	Type                 FilesystemVersion_VersionType `protobuf:"varint,1,opt,name=Type,proto3,enum=FilesystemVersion_VersionType" json:"Type,omitempty"`
	Name                 string                        `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Guid                 uint64                        `protobuf:"varint,3,opt,name=Guid,proto3" json:"Guid,omitempty"`
	CreateTXG            uint64                        `protobuf:"varint,4,opt,name=CreateTXG,proto3" json:"CreateTXG,omitempty"`
	Creation             string                        `protobuf:"bytes,5,opt,name=Creation,proto3" json:"Creation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *FilesystemVersion) Reset()         { *m = FilesystemVersion{} }
func (m *FilesystemVersion) String() string { return proto.CompactTextString(m) }
func (*FilesystemVersion) ProtoMessage()    {}
func (*FilesystemVersion) Descriptor() ([]byte, []int) {
	return fileDescriptor_368839fb4f2ad628, []int{5}
}

func (m *FilesystemVersion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilesystemVersion.Unmarshal(m, b)
}
func (m *FilesystemVersion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilesystemVersion.Marshal(b, m, deterministic)
}
func (m *FilesystemVersion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilesystemVersion.Merge(m, src)
}
func (m *FilesystemVersion) XXX_Size() int {
	return xxx_messageInfo_FilesystemVersion.Size(m)
}
func (m *FilesystemVersion) XXX_DiscardUnknown() {
	xxx_messageInfo_FilesystemVersion.DiscardUnknown(m)
}

var xxx_messageInfo_FilesystemVersion proto.InternalMessageInfo

func (m *FilesystemVersion) GetType() FilesystemVersion_VersionType {
	if m != nil {
		return m.Type
	}
	return FilesystemVersion_Snapshot
}

func (m *FilesystemVersion) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FilesystemVersion) GetGuid() uint64 {
	if m != nil {
		return m.Guid
	}
	return 0
}

func (m *FilesystemVersion) GetCreateTXG() uint64 {
	if m != nil {
		return m.CreateTXG
	}
	return 0
}

func (m *FilesystemVersion) GetCreation() string {
	if m != nil {
		return m.Creation
	}
	return ""
}

type SendReq struct {
	Filesystem string `protobuf:"bytes,1,opt,name=Filesystem,proto3" json:"Filesystem,omitempty"`
	From       string `protobuf:"bytes,2,opt,name=From,proto3" json:"From,omitempty"`
	// May be empty / null to request a full transfer of From
	To string `protobuf:"bytes,3,opt,name=To,proto3" json:"To,omitempty"`
	// If ResumeToken is not empty, the resume token that CAN be tried for 'zfs send' by the sender.
	// The sender MUST indicate in SendRes.UsedResumeToken
	// If it does not work, the sender SHOULD clear the resume token on their side
	// and use From and To instead
	// If ResumeToken is not empty, the GUIDs of From and To
	// MUST correspond to those encoded in the ResumeToken.
	// Otherwise, the Sender MUST return an error.
	ResumeToken          string   `protobuf:"bytes,4,opt,name=ResumeToken,proto3" json:"ResumeToken,omitempty"`
	Compress             bool     `protobuf:"varint,5,opt,name=Compress,proto3" json:"Compress,omitempty"`
	Dedup                bool     `protobuf:"varint,6,opt,name=Dedup,proto3" json:"Dedup,omitempty"`
	DryRun               bool     `protobuf:"varint,7,opt,name=DryRun,proto3" json:"DryRun,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendReq) Reset()         { *m = SendReq{} }
func (m *SendReq) String() string { return proto.CompactTextString(m) }
func (*SendReq) ProtoMessage()    {}
func (*SendReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_368839fb4f2ad628, []int{6}
}

func (m *SendReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendReq.Unmarshal(m, b)
}
func (m *SendReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendReq.Marshal(b, m, deterministic)
}
func (m *SendReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendReq.Merge(m, src)
}
func (m *SendReq) XXX_Size() int {
	return xxx_messageInfo_SendReq.Size(m)
}
func (m *SendReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SendReq.DiscardUnknown(m)
}

var xxx_messageInfo_SendReq proto.InternalMessageInfo

func (m *SendReq) GetFilesystem() string {
	if m != nil {
		return m.Filesystem
	}
	return ""
}

func (m *SendReq) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *SendReq) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *SendReq) GetResumeToken() string {
	if m != nil {
		return m.ResumeToken
	}
	return ""
}

func (m *SendReq) GetCompress() bool {
	if m != nil {
		return m.Compress
	}
	return false
}

func (m *SendReq) GetDedup() bool {
	if m != nil {
		return m.Dedup
	}
	return false
}

func (m *SendReq) GetDryRun() bool {
	if m != nil {
		return m.DryRun
	}
	return false
}

type Property struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Property) Reset()         { *m = Property{} }
func (m *Property) String() string { return proto.CompactTextString(m) }
func (*Property) ProtoMessage()    {}
func (*Property) Descriptor() ([]byte, []int) {
	return fileDescriptor_368839fb4f2ad628, []int{7}
}

func (m *Property) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Property.Unmarshal(m, b)
}
func (m *Property) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Property.Marshal(b, m, deterministic)
}
func (m *Property) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Property.Merge(m, src)
}
func (m *Property) XXX_Size() int {
	return xxx_messageInfo_Property.Size(m)
}
func (m *Property) XXX_DiscardUnknown() {
	xxx_messageInfo_Property.DiscardUnknown(m)
}

var xxx_messageInfo_Property proto.InternalMessageInfo

func (m *Property) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Property) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type SendRes struct {
	// The actual stream is sent over antoher mechanism.
	// The client passes the following otken via that mechanism to restore context on the sender.
	SendToken string `protobuf:"bytes,1,opt,name=SendToken,proto3" json:"SendToken,omitempty"`
	// Whether the resume token provided in the request has been used or not.
	UsedResumeToken bool `protobuf:"varint,2,opt,name=UsedResumeToken,proto3" json:"UsedResumeToken,omitempty"`
	// Expected stream size determined by dry run, not exact.
	// 0 indicates that for the given SendReq, no size estimate could be made.
	ExpectedSize         int64       `protobuf:"varint,3,opt,name=ExpectedSize,proto3" json:"ExpectedSize,omitempty"`
	Properties           []*Property `protobuf:"bytes,4,rep,name=Properties,proto3" json:"Properties,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SendRes) Reset()         { *m = SendRes{} }
func (m *SendRes) String() string { return proto.CompactTextString(m) }
func (*SendRes) ProtoMessage()    {}
func (*SendRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_368839fb4f2ad628, []int{8}
}

func (m *SendRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendRes.Unmarshal(m, b)
}
func (m *SendRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendRes.Marshal(b, m, deterministic)
}
func (m *SendRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendRes.Merge(m, src)
}
func (m *SendRes) XXX_Size() int {
	return xxx_messageInfo_SendRes.Size(m)
}
func (m *SendRes) XXX_DiscardUnknown() {
	xxx_messageInfo_SendRes.DiscardUnknown(m)
}

var xxx_messageInfo_SendRes proto.InternalMessageInfo

func (m *SendRes) GetSendToken() string {
	if m != nil {
		return m.SendToken
	}
	return ""
}

func (m *SendRes) GetUsedResumeToken() bool {
	if m != nil {
		return m.UsedResumeToken
	}
	return false
}

func (m *SendRes) GetExpectedSize() int64 {
	if m != nil {
		return m.ExpectedSize
	}
	return 0
}

func (m *SendRes) GetProperties() []*Property {
	if m != nil {
		return m.Properties
	}
	return nil
}

type ReceiveReq struct {
	// The stream part of the streamrpc request contains the zfs send stream
	Filesystem string `protobuf:"bytes,1,opt,name=Filesystem,proto3" json:"Filesystem,omitempty"`
	// If true, the receiver should clear the resume token before perfoming the zfs recv of the stream in the request
	ClearResumeToken     bool     `protobuf:"varint,2,opt,name=ClearResumeToken,proto3" json:"ClearResumeToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceiveReq) Reset()         { *m = ReceiveReq{} }
func (m *ReceiveReq) String() string { return proto.CompactTextString(m) }
func (*ReceiveReq) ProtoMessage()    {}
func (*ReceiveReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_368839fb4f2ad628, []int{9}
}

func (m *ReceiveReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiveReq.Unmarshal(m, b)
}
func (m *ReceiveReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiveReq.Marshal(b, m, deterministic)
}
func (m *ReceiveReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiveReq.Merge(m, src)
}
func (m *ReceiveReq) XXX_Size() int {
	return xxx_messageInfo_ReceiveReq.Size(m)
}
func (m *ReceiveReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiveReq.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiveReq proto.InternalMessageInfo

func (m *ReceiveReq) GetFilesystem() string {
	if m != nil {
		return m.Filesystem
	}
	return ""
}

func (m *ReceiveReq) GetClearResumeToken() bool {
	if m != nil {
		return m.ClearResumeToken
	}
	return false
}

type ReceiveRes struct {
	// The actual stream is sent over antoher mechanism.
	// The client passes the following otken via that mechanism to restore context on the sender.
	ReceiveToken         string   `protobuf:"bytes,1,opt,name=ReceiveToken,proto3" json:"ReceiveToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceiveRes) Reset()         { *m = ReceiveRes{} }
func (m *ReceiveRes) String() string { return proto.CompactTextString(m) }
func (*ReceiveRes) ProtoMessage()    {}
func (*ReceiveRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_368839fb4f2ad628, []int{10}
}

func (m *ReceiveRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiveRes.Unmarshal(m, b)
}
func (m *ReceiveRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiveRes.Marshal(b, m, deterministic)
}
func (m *ReceiveRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiveRes.Merge(m, src)
}
func (m *ReceiveRes) XXX_Size() int {
	return xxx_messageInfo_ReceiveRes.Size(m)
}
func (m *ReceiveRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiveRes.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiveRes proto.InternalMessageInfo

func (m *ReceiveRes) GetReceiveToken() string {
	if m != nil {
		return m.ReceiveToken
	}
	return ""
}

type DestroySnapshotsReq struct {
	Filesystem string `protobuf:"bytes,1,opt,name=Filesystem,proto3" json:"Filesystem,omitempty"`
	// Path to filesystem, snapshot or bookmark to be destroyed
	Snapshots            []*FilesystemVersion `protobuf:"bytes,2,rep,name=Snapshots,proto3" json:"Snapshots,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DestroySnapshotsReq) Reset()         { *m = DestroySnapshotsReq{} }
func (m *DestroySnapshotsReq) String() string { return proto.CompactTextString(m) }
func (*DestroySnapshotsReq) ProtoMessage()    {}
func (*DestroySnapshotsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_368839fb4f2ad628, []int{11}
}

func (m *DestroySnapshotsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DestroySnapshotsReq.Unmarshal(m, b)
}
func (m *DestroySnapshotsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DestroySnapshotsReq.Marshal(b, m, deterministic)
}
func (m *DestroySnapshotsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DestroySnapshotsReq.Merge(m, src)
}
func (m *DestroySnapshotsReq) XXX_Size() int {
	return xxx_messageInfo_DestroySnapshotsReq.Size(m)
}
func (m *DestroySnapshotsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DestroySnapshotsReq.DiscardUnknown(m)
}

var xxx_messageInfo_DestroySnapshotsReq proto.InternalMessageInfo

func (m *DestroySnapshotsReq) GetFilesystem() string {
	if m != nil {
		return m.Filesystem
	}
	return ""
}

func (m *DestroySnapshotsReq) GetSnapshots() []*FilesystemVersion {
	if m != nil {
		return m.Snapshots
	}
	return nil
}

type DestroySnapshotRes struct {
	Snapshot             *FilesystemVersion `protobuf:"bytes,1,opt,name=Snapshot,proto3" json:"Snapshot,omitempty"`
	Error                string             `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *DestroySnapshotRes) Reset()         { *m = DestroySnapshotRes{} }
func (m *DestroySnapshotRes) String() string { return proto.CompactTextString(m) }
func (*DestroySnapshotRes) ProtoMessage()    {}
func (*DestroySnapshotRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_368839fb4f2ad628, []int{12}
}

func (m *DestroySnapshotRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DestroySnapshotRes.Unmarshal(m, b)
}
func (m *DestroySnapshotRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DestroySnapshotRes.Marshal(b, m, deterministic)
}
func (m *DestroySnapshotRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DestroySnapshotRes.Merge(m, src)
}
func (m *DestroySnapshotRes) XXX_Size() int {
	return xxx_messageInfo_DestroySnapshotRes.Size(m)
}
func (m *DestroySnapshotRes) XXX_DiscardUnknown() {
	xxx_messageInfo_DestroySnapshotRes.DiscardUnknown(m)
}

var xxx_messageInfo_DestroySnapshotRes proto.InternalMessageInfo

func (m *DestroySnapshotRes) GetSnapshot() *FilesystemVersion {
	if m != nil {
		return m.Snapshot
	}
	return nil
}

func (m *DestroySnapshotRes) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type DestroySnapshotsRes struct {
	Results              []*DestroySnapshotRes `protobuf:"bytes,1,rep,name=Results,proto3" json:"Results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *DestroySnapshotsRes) Reset()         { *m = DestroySnapshotsRes{} }
func (m *DestroySnapshotsRes) String() string { return proto.CompactTextString(m) }
func (*DestroySnapshotsRes) ProtoMessage()    {}
func (*DestroySnapshotsRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_368839fb4f2ad628, []int{13}
}

func (m *DestroySnapshotsRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DestroySnapshotsRes.Unmarshal(m, b)
}
func (m *DestroySnapshotsRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DestroySnapshotsRes.Marshal(b, m, deterministic)
}
func (m *DestroySnapshotsRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DestroySnapshotsRes.Merge(m, src)
}
func (m *DestroySnapshotsRes) XXX_Size() int {
	return xxx_messageInfo_DestroySnapshotsRes.Size(m)
}
func (m *DestroySnapshotsRes) XXX_DiscardUnknown() {
	xxx_messageInfo_DestroySnapshotsRes.DiscardUnknown(m)
}

var xxx_messageInfo_DestroySnapshotsRes proto.InternalMessageInfo

func (m *DestroySnapshotsRes) GetResults() []*DestroySnapshotRes {
	if m != nil {
		return m.Results
	}
	return nil
}

type ReplicationCursorReq struct {
	Filesystem string `protobuf:"bytes,1,opt,name=Filesystem,proto3" json:"Filesystem,omitempty"`
	// Types that are valid to be assigned to Op:
	//	*ReplicationCursorReq_Get
	//	*ReplicationCursorReq_Set
	Op                   isReplicationCursorReq_Op `protobuf_oneof:"op"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ReplicationCursorReq) Reset()         { *m = ReplicationCursorReq{} }
func (m *ReplicationCursorReq) String() string { return proto.CompactTextString(m) }
func (*ReplicationCursorReq) ProtoMessage()    {}
func (*ReplicationCursorReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_368839fb4f2ad628, []int{14}
}

func (m *ReplicationCursorReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplicationCursorReq.Unmarshal(m, b)
}
func (m *ReplicationCursorReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplicationCursorReq.Marshal(b, m, deterministic)
}
func (m *ReplicationCursorReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplicationCursorReq.Merge(m, src)
}
func (m *ReplicationCursorReq) XXX_Size() int {
	return xxx_messageInfo_ReplicationCursorReq.Size(m)
}
func (m *ReplicationCursorReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplicationCursorReq.DiscardUnknown(m)
}

var xxx_messageInfo_ReplicationCursorReq proto.InternalMessageInfo

func (m *ReplicationCursorReq) GetFilesystem() string {
	if m != nil {
		return m.Filesystem
	}
	return ""
}

type isReplicationCursorReq_Op interface {
	isReplicationCursorReq_Op()
}

type ReplicationCursorReq_Get struct {
	Get *ReplicationCursorReq_GetOp `protobuf:"bytes,2,opt,name=get,proto3,oneof"`
}

type ReplicationCursorReq_Set struct {
	Set *ReplicationCursorReq_SetOp `protobuf:"bytes,3,opt,name=set,proto3,oneof"`
}

func (*ReplicationCursorReq_Get) isReplicationCursorReq_Op() {}

func (*ReplicationCursorReq_Set) isReplicationCursorReq_Op() {}

func (m *ReplicationCursorReq) GetOp() isReplicationCursorReq_Op {
	if m != nil {
		return m.Op
	}
	return nil
}

func (m *ReplicationCursorReq) GetGet() *ReplicationCursorReq_GetOp {
	if x, ok := m.GetOp().(*ReplicationCursorReq_Get); ok {
		return x.Get
	}
	return nil
}

func (m *ReplicationCursorReq) GetSet() *ReplicationCursorReq_SetOp {
	if x, ok := m.GetOp().(*ReplicationCursorReq_Set); ok {
		return x.Set
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ReplicationCursorReq) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ReplicationCursorReq_OneofMarshaler, _ReplicationCursorReq_OneofUnmarshaler, _ReplicationCursorReq_OneofSizer, []interface{}{
		(*ReplicationCursorReq_Get)(nil),
		(*ReplicationCursorReq_Set)(nil),
	}
}

func _ReplicationCursorReq_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ReplicationCursorReq)
	// op
	switch x := m.Op.(type) {
	case *ReplicationCursorReq_Get:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Get); err != nil {
			return err
		}
	case *ReplicationCursorReq_Set:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Set); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("ReplicationCursorReq.Op has unexpected type %T", x)
	}
	return nil
}

func _ReplicationCursorReq_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ReplicationCursorReq)
	switch tag {
	case 2: // op.get
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ReplicationCursorReq_GetOp)
		err := b.DecodeMessage(msg)
		m.Op = &ReplicationCursorReq_Get{msg}
		return true, err
	case 3: // op.set
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ReplicationCursorReq_SetOp)
		err := b.DecodeMessage(msg)
		m.Op = &ReplicationCursorReq_Set{msg}
		return true, err
	default:
		return false, nil
	}
}

func _ReplicationCursorReq_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ReplicationCursorReq)
	// op
	switch x := m.Op.(type) {
	case *ReplicationCursorReq_Get:
		s := proto.Size(x.Get)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ReplicationCursorReq_Set:
		s := proto.Size(x.Set)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type ReplicationCursorReq_GetOp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplicationCursorReq_GetOp) Reset()         { *m = ReplicationCursorReq_GetOp{} }
func (m *ReplicationCursorReq_GetOp) String() string { return proto.CompactTextString(m) }
func (*ReplicationCursorReq_GetOp) ProtoMessage()    {}
func (*ReplicationCursorReq_GetOp) Descriptor() ([]byte, []int) {
	return fileDescriptor_368839fb4f2ad628, []int{14, 0}
}

func (m *ReplicationCursorReq_GetOp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplicationCursorReq_GetOp.Unmarshal(m, b)
}
func (m *ReplicationCursorReq_GetOp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplicationCursorReq_GetOp.Marshal(b, m, deterministic)
}
func (m *ReplicationCursorReq_GetOp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplicationCursorReq_GetOp.Merge(m, src)
}
func (m *ReplicationCursorReq_GetOp) XXX_Size() int {
	return xxx_messageInfo_ReplicationCursorReq_GetOp.Size(m)
}
func (m *ReplicationCursorReq_GetOp) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplicationCursorReq_GetOp.DiscardUnknown(m)
}

var xxx_messageInfo_ReplicationCursorReq_GetOp proto.InternalMessageInfo

type ReplicationCursorReq_SetOp struct {
	Snapshot             string   `protobuf:"bytes,2,opt,name=Snapshot,proto3" json:"Snapshot,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplicationCursorReq_SetOp) Reset()         { *m = ReplicationCursorReq_SetOp{} }
func (m *ReplicationCursorReq_SetOp) String() string { return proto.CompactTextString(m) }
func (*ReplicationCursorReq_SetOp) ProtoMessage()    {}
func (*ReplicationCursorReq_SetOp) Descriptor() ([]byte, []int) {
	return fileDescriptor_368839fb4f2ad628, []int{14, 1}
}

func (m *ReplicationCursorReq_SetOp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplicationCursorReq_SetOp.Unmarshal(m, b)
}
func (m *ReplicationCursorReq_SetOp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplicationCursorReq_SetOp.Marshal(b, m, deterministic)
}
func (m *ReplicationCursorReq_SetOp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplicationCursorReq_SetOp.Merge(m, src)
}
func (m *ReplicationCursorReq_SetOp) XXX_Size() int {
	return xxx_messageInfo_ReplicationCursorReq_SetOp.Size(m)
}
func (m *ReplicationCursorReq_SetOp) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplicationCursorReq_SetOp.DiscardUnknown(m)
}

var xxx_messageInfo_ReplicationCursorReq_SetOp proto.InternalMessageInfo

func (m *ReplicationCursorReq_SetOp) GetSnapshot() string {
	if m != nil {
		return m.Snapshot
	}
	return ""
}

type ReplicationCursorRes struct {
	// Types that are valid to be assigned to Result:
	//	*ReplicationCursorRes_Guid
	//	*ReplicationCursorRes_Error
	Result               isReplicationCursorRes_Result `protobuf_oneof:"Result"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *ReplicationCursorRes) Reset()         { *m = ReplicationCursorRes{} }
func (m *ReplicationCursorRes) String() string { return proto.CompactTextString(m) }
func (*ReplicationCursorRes) ProtoMessage()    {}
func (*ReplicationCursorRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_368839fb4f2ad628, []int{15}
}

func (m *ReplicationCursorRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplicationCursorRes.Unmarshal(m, b)
}
func (m *ReplicationCursorRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplicationCursorRes.Marshal(b, m, deterministic)
}
func (m *ReplicationCursorRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplicationCursorRes.Merge(m, src)
}
func (m *ReplicationCursorRes) XXX_Size() int {
	return xxx_messageInfo_ReplicationCursorRes.Size(m)
}
func (m *ReplicationCursorRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplicationCursorRes.DiscardUnknown(m)
}

var xxx_messageInfo_ReplicationCursorRes proto.InternalMessageInfo

type isReplicationCursorRes_Result interface {
	isReplicationCursorRes_Result()
}

type ReplicationCursorRes_Guid struct {
	Guid uint64 `protobuf:"varint,1,opt,name=Guid,proto3,oneof"`
}

type ReplicationCursorRes_Error struct {
	Error string `protobuf:"bytes,2,opt,name=Error,proto3,oneof"`
}

func (*ReplicationCursorRes_Guid) isReplicationCursorRes_Result() {}

func (*ReplicationCursorRes_Error) isReplicationCursorRes_Result() {}

func (m *ReplicationCursorRes) GetResult() isReplicationCursorRes_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *ReplicationCursorRes) GetGuid() uint64 {
	if x, ok := m.GetResult().(*ReplicationCursorRes_Guid); ok {
		return x.Guid
	}
	return 0
}

func (m *ReplicationCursorRes) GetError() string {
	if x, ok := m.GetResult().(*ReplicationCursorRes_Error); ok {
		return x.Error
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ReplicationCursorRes) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ReplicationCursorRes_OneofMarshaler, _ReplicationCursorRes_OneofUnmarshaler, _ReplicationCursorRes_OneofSizer, []interface{}{
		(*ReplicationCursorRes_Guid)(nil),
		(*ReplicationCursorRes_Error)(nil),
	}
}

func _ReplicationCursorRes_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ReplicationCursorRes)
	// Result
	switch x := m.Result.(type) {
	case *ReplicationCursorRes_Guid:
		b.EncodeVarint(1<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.Guid))
	case *ReplicationCursorRes_Error:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Error)
	case nil:
	default:
		return fmt.Errorf("ReplicationCursorRes.Result has unexpected type %T", x)
	}
	return nil
}

func _ReplicationCursorRes_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ReplicationCursorRes)
	switch tag {
	case 1: // Result.Guid
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Result = &ReplicationCursorRes_Guid{x}
		return true, err
	case 2: // Result.Error
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Result = &ReplicationCursorRes_Error{x}
		return true, err
	default:
		return false, nil
	}
}

func _ReplicationCursorRes_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ReplicationCursorRes)
	// Result
	switch x := m.Result.(type) {
	case *ReplicationCursorRes_Guid:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.Guid))
	case *ReplicationCursorRes_Error:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Error)))
		n += len(x.Error)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterEnum("FilesystemVersion_VersionType", FilesystemVersion_VersionType_name, FilesystemVersion_VersionType_value)
	proto.RegisterType((*ListFilesystemReq)(nil), "ListFilesystemReq")
	proto.RegisterType((*ListFilesystemRes)(nil), "ListFilesystemRes")
	proto.RegisterType((*Filesystem)(nil), "Filesystem")
	proto.RegisterType((*ListFilesystemVersionsReq)(nil), "ListFilesystemVersionsReq")
	proto.RegisterType((*ListFilesystemVersionsRes)(nil), "ListFilesystemVersionsRes")
	proto.RegisterType((*FilesystemVersion)(nil), "FilesystemVersion")
	proto.RegisterType((*SendReq)(nil), "SendReq")
	proto.RegisterType((*Property)(nil), "Property")
	proto.RegisterType((*SendRes)(nil), "SendRes")
	proto.RegisterType((*ReceiveReq)(nil), "ReceiveReq")
	proto.RegisterType((*ReceiveRes)(nil), "ReceiveRes")
	proto.RegisterType((*DestroySnapshotsReq)(nil), "DestroySnapshotsReq")
	proto.RegisterType((*DestroySnapshotRes)(nil), "DestroySnapshotRes")
	proto.RegisterType((*DestroySnapshotsRes)(nil), "DestroySnapshotsRes")
	proto.RegisterType((*ReplicationCursorReq)(nil), "ReplicationCursorReq")
	proto.RegisterType((*ReplicationCursorReq_GetOp)(nil), "ReplicationCursorReq.GetOp")
	proto.RegisterType((*ReplicationCursorReq_SetOp)(nil), "ReplicationCursorReq.SetOp")
	proto.RegisterType((*ReplicationCursorRes)(nil), "ReplicationCursorRes")
}

func init() { proto.RegisterFile("replication/pdu/pdu.proto", fileDescriptor_368839fb4f2ad628) }

var fileDescriptor_368839fb4f2ad628 = []byte{
	// 774 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0xef, 0x8e, 0xda, 0x46,
	0x10, 0xc7, 0x60, 0xc0, 0x0c, 0x51, 0xc2, 0xcd, 0xd1, 0x93, 0xe3, 0x56, 0x11, 0xda, 0x7c, 0x21,
	0x95, 0xea, 0x44, 0xb4, 0x5f, 0xaa, 0x4a, 0x95, 0xca, 0x91, 0xdc, 0x49, 0xad, 0xd2, 0xd3, 0x42,
	0xa3, 0x28, 0xdf, 0xdc, 0x63, 0x94, 0xb3, 0x0e, 0x58, 0xdf, 0xae, 0x7d, 0x2a, 0x7d, 0x9a, 0xbe,
	0x46, 0xdf, 0xa1, 0x1f, 0xfb, 0x08, 0x7d, 0x90, 0x6a, 0xd7, 0x7f, 0x30, 0xd8, 0x48, 0x7c, 0x40,
	0xec, 0xef, 0x37, 0xb3, 0xbb, 0x33, 0xbf, 0x9d, 0x19, 0xc3, 0x73, 0x49, 0xd1, 0x2a, 0xbc, 0x0d,
	0xe2, 0x50, 0x6c, 0x5e, 0x47, 0xcb, 0x44, 0xff, 0xfc, 0x48, 0x8a, 0x58, 0xb0, 0x73, 0x38, 0xfb,
	0x25, 0x54, 0xf1, 0xbb, 0x70, 0x45, 0x6a, 0xab, 0x62, 0x5a, 0x73, 0x7a, 0x60, 0xd3, 0x2a, 0xa9,
	0xf0, 0x1b, 0xe8, 0xef, 0x08, 0xe5, 0x5a, 0xa3, 0xd6, 0xb8, 0x3f, 0xe9, 0xfb, 0x25, 0xa7, 0xb2,
	0x9d, 0x4d, 0x01, 0x76, 0x10, 0x11, 0xec, 0x9b, 0x20, 0xbe, 0x73, 0xad, 0x91, 0x35, 0xee, 0x71,
	0xb3, 0xc6, 0x11, 0xf4, 0x39, 0xa9, 0x64, 0x4d, 0x0b, 0x71, 0x4f, 0x1b, 0xb7, 0x69, 0x4c, 0x65,
	0x8a, 0xfd, 0x00, 0xcf, 0xf7, 0xe3, 0xf8, 0x40, 0x52, 0x85, 0x62, 0xa3, 0x38, 0x3d, 0xe0, 0x8b,
	0xf2, 0x05, 0xd9, 0xc1, 0x25, 0x86, 0xfd, 0x7c, 0x7c, 0xb3, 0x42, 0x1f, 0x9c, 0x1c, 0x66, 0x99,
	0xa0, 0x5f, 0xf1, 0xe4, 0x85, 0x0f, 0xfb, 0xd7, 0x82, 0xb3, 0x8a, 0x1d, 0x27, 0x60, 0x2f, 0xb6,
	0x11, 0x99, 0xcb, 0x9f, 0x4e, 0x5e, 0x54, 0x4f, 0xf0, 0xb3, 0x7f, 0xed, 0xc5, 0x8d, 0xaf, 0x56,
	0xe2, 0x7d, 0xb0, 0xa6, 0x2c, 0x5d, 0xb3, 0xd6, 0xdc, 0x55, 0x12, 0x2e, 0xdd, 0xd6, 0xc8, 0x1a,
	0xdb, 0xdc, 0xac, 0xf1, 0x2b, 0xe8, 0x5d, 0x4a, 0x0a, 0x62, 0x5a, 0x7c, 0xbc, 0x72, 0x6d, 0x63,
	0xd8, 0x11, 0xe8, 0x81, 0x63, 0x40, 0x28, 0x36, 0x6e, 0xdb, 0x9c, 0x54, 0x60, 0xf6, 0x0a, 0xfa,
	0xa5, 0x6b, 0xf1, 0x09, 0x38, 0xf3, 0x4d, 0x10, 0xa9, 0x3b, 0x11, 0x0f, 0x1a, 0x1a, 0x4d, 0x85,
	0xb8, 0x5f, 0x07, 0xf2, 0x7e, 0x60, 0xb1, 0xbf, 0x2d, 0xe8, 0xce, 0x69, 0xb3, 0x3c, 0x41, 0x4f,
	0x1d, 0xe4, 0x3b, 0x29, 0xd6, 0x79, 0xe0, 0x7a, 0x8d, 0x4f, 0xa1, 0xb9, 0x10, 0x26, 0xec, 0x1e,
	0x6f, 0x2e, 0xc4, 0xe1, 0x93, 0xda, 0x95, 0x27, 0x35, 0x81, 0x8b, 0x75, 0x24, 0x49, 0x29, 0x13,
	0xb8, 0xc3, 0x0b, 0x8c, 0x43, 0x68, 0xcf, 0x68, 0x99, 0x44, 0x6e, 0xc7, 0x18, 0x52, 0x80, 0x17,
	0xd0, 0x99, 0xc9, 0x2d, 0x4f, 0x36, 0x6e, 0xd7, 0xd0, 0x19, 0x62, 0xdf, 0x81, 0x73, 0x23, 0x45,
	0x44, 0x32, 0xde, 0x16, 0xa2, 0x5a, 0x25, 0x51, 0x87, 0xd0, 0xfe, 0x10, 0xac, 0x92, 0x5c, 0xe9,
	0x14, 0xb0, 0xbf, 0x8a, 0x8c, 0x95, 0x96, 0x58, 0x2f, 0xd3, 0x58, 0xd3, 0xad, 0x3b, 0x02, 0xc7,
	0xf0, 0xec, 0x37, 0x45, 0xcb, 0xc3, 0x12, 0x75, 0xf8, 0x21, 0x8d, 0x0c, 0x9e, 0xbc, 0xfd, 0x23,
	0xa2, 0xdb, 0x98, 0x96, 0xf3, 0xf0, 0x4f, 0x32, 0x7a, 0xb4, 0xf8, 0x1e, 0x87, 0xaf, 0x00, 0xb2,
	0x68, 0x43, 0x52, 0xae, 0x6d, 0x4a, 0xae, 0xe7, 0xe7, 0x09, 0xf0, 0x92, 0x91, 0x7d, 0x04, 0xe0,
	0x74, 0x4b, 0xe1, 0x23, 0x9d, 0xf2, 0x2c, 0x5f, 0xc3, 0xe0, 0x72, 0x45, 0x81, 0xac, 0xc6, 0x59,
	0xe1, 0xd9, 0x9b, 0xd2, 0xc9, 0x4a, 0x87, 0x9d, 0xa1, 0xb2, 0x02, 0x7b, 0x1c, 0xfb, 0x0c, 0xe7,
	0x33, 0x52, 0xb1, 0x14, 0xdb, 0xbc, 0x86, 0x4e, 0xe9, 0x3d, 0x7c, 0x03, 0xbd, 0xc2, 0xdf, 0x6d,
	0x1e, 0xed, 0xaf, 0x9d, 0x13, 0xfb, 0x04, 0x78, 0x70, 0x51, 0xd6, 0xa6, 0x39, 0x34, 0xb7, 0x1c,
	0x69, 0xd3, 0xdc, 0x47, 0xbf, 0xf9, 0x5b, 0x29, 0x85, 0xcc, 0xdf, 0xdc, 0x00, 0x36, 0xab, 0x4b,
	0x42, 0x0f, 0xb4, 0xae, 0x16, 0x67, 0x15, 0xe7, 0x23, 0xe0, 0xdc, 0xaf, 0x86, 0xc0, 0x73, 0x1f,
	0xf6, 0x8f, 0x05, 0x43, 0xbe, 0x9b, 0xa3, 0x97, 0x89, 0x54, 0x42, 0x9e, 0x22, 0xc6, 0x6b, 0x68,
	0x7d, 0xa6, 0xd8, 0x84, 0xd4, 0x9f, 0x7c, 0xe9, 0xd7, 0x9d, 0xe1, 0x5f, 0x51, 0xfc, 0x6b, 0x74,
	0xdd, 0xe0, 0xda, 0x53, 0x6f, 0x50, 0x14, 0x9b, 0x32, 0x3a, 0xba, 0x61, 0x9e, 0x6f, 0x50, 0x14,
	0x7b, 0x5d, 0x68, 0x9b, 0x03, 0xbc, 0x97, 0xd0, 0x36, 0x06, 0xdd, 0x66, 0x85, 0x70, 0xa9, 0x16,
	0x05, 0x9e, 0xda, 0xd0, 0x14, 0x11, 0x7b, 0x5f, 0x9b, 0x8d, 0x6e, 0xc2, 0x74, 0x16, 0xe9, 0x3c,
	0xec, 0xeb, 0x46, 0x36, 0x8d, 0x2e, 0xf6, 0x84, 0xbd, 0x6e, 0x64, 0xd2, 0x4e, 0x1d, 0xe8, 0xa4,
	0xfa, 0x4c, 0xfe, 0x6b, 0xc2, 0x59, 0xe9, 0xc0, 0x39, 0xc9, 0x47, 0x92, 0xf8, 0x3d, 0x3c, 0xdb,
	0x1f, 0xc2, 0x0a, 0xd1, 0xaf, 0x7c, 0x70, 0xbc, 0x2a, 0xa7, 0xf0, 0x06, 0x2e, 0xea, 0xe7, 0x37,
	0x7a, 0xfe, 0xd1, 0xaf, 0x82, 0x77, 0xdc, 0xa6, 0xf0, 0x47, 0x18, 0x1c, 0xd6, 0x01, 0x0e, 0xfd,
	0x9a, 0xfa, 0xf6, 0xea, 0x58, 0x85, 0x3f, 0xed, 0x65, 0x98, 0x4a, 0x86, 0x5f, 0xd4, 0xbe, 0x8f,
	0x57, 0x4b, 0x2b, 0xf4, 0xc0, 0xd6, 0x13, 0x06, 0x1d, 0x3f, 0x1b, 0xbb, 0x5e, 0xbe, 0x52, 0xf8,
	0x52, 0xd7, 0xa3, 0xe9, 0x3d, 0xec, 0xfb, 0xbb, 0x09, 0xe0, 0x95, 0x80, 0x9a, 0xb6, 0x3f, 0xb5,
	0xa2, 0x65, 0xf2, 0x7b, 0xc7, 0x7c, 0xbd, 0xbf, 0xfd, 0x3f, 0x00, 0x00, 0xff, 0xff, 0x19, 0xf5,
	0x26, 0x6c, 0xda, 0x07, 0x00, 0x00,
}
